package com.otectus.otessmithing.client.compat.jei;

import com.otectus.otessmithing.OtesSmithing;
import com.otectus.otessmithing.item.SmithingTier;
import com.otectus.otessmithing.recipe.SmithingRecipe;
import com.otectus.otessmithing.registry.ModItems;
import com.otectus.otessmithing.registry.ModRecipeTypes;
import mezz.jei.api.IModPlugin;
import mezz.jei.api.JeiPlugin;
import mezz.jei.api.registration.IRecipeCatalystRegistration;
import mezz.jei.api.registration.IRecipeCategoryRegistration;
import mezz.jei.api.registration.IRecipeRegistration;
import net.minecraft.client.Minecraft;
import net.minecraft.core.registries.BuiltInRegistries;
import net.minecraft.network.chat.Component;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.world.item.ItemStack;

import java.util.ArrayList;
import java.util.Comparator;
import java.util.List;

/**
 * JEI support. The client recipe manager already contains every active smithing recipe - explicit ones and
 * those generated by automatic detection - and no longer contains the crafting recipes the server disabled,
 * so JEI shows exactly the rules the server enforces.
 */
@JeiPlugin
public class OtesSmithingJeiPlugin implements IModPlugin {
    private static final ResourceLocation UID = OtesSmithing.id("jei_plugin");

    @Override
    public ResourceLocation getPluginUid() {
        return UID;
    }

    @Override
    public void registerCategories(IRecipeCategoryRegistration registration) {
        registration.addRecipeCategories(new SmithingRecipeCategory(registration.getJeiHelpers().getGuiHelper()));
    }

    @Override
    public void registerRecipes(IRecipeRegistration registration) {
        if (Minecraft.getInstance().level == null) return;
        List<SmithingRecipe> recipes = new ArrayList<>(Minecraft.getInstance().level.getRecipeManager()
                .getAllRecipesFor(ModRecipeTypes.SMITHING.get()));
        recipes.sort(Comparator.comparing(r -> BuiltInRegistries.ITEM.getKey(r.resultItem()).toString()));
        registration.addRecipes(SmithingRecipeCategory.TYPE, recipes);

        for (SmithingTier tier : SmithingTier.values()) {
            registration.addItemStackInfo(new ItemStack(ModItems.tongs(tier)), Component.translatable("jei.otes_smithing.info.tongs"));
            registration.addItemStackInfo(new ItemStack(ModItems.hammer(tier)), Component.translatable("jei.otes_smithing.info.hammer"));
        }
        registration.addItemStackInfo(new ItemStack(ModItems.SMITHS_FORGE.get()), Component.translatable("jei.otes_smithing.info.forge"));
        registration.addItemStackInfo(new ItemStack(ModItems.SMITHS_ANVIL.get()), Component.translatable("jei.otes_smithing.info.anvil"));
        registration.addItemStackInfo(new ItemStack(ModItems.SMITHS_TROUGH.get()), Component.translatable("jei.otes_smithing.info.trough"));
        registration.addItemStackInfo(new ItemStack(ModItems.SMITHS_GRINDSTONE.get()), Component.translatable("jei.otes_smithing.info.grindstone"));
    }

    @Override
    public void registerRecipeCatalysts(IRecipeCatalystRegistration registration) {
        registration.addRecipeCatalyst(new ItemStack(ModItems.SMITHS_FORGE.get()), SmithingRecipeCategory.TYPE);
        registration.addRecipeCatalyst(new ItemStack(ModItems.SMITHS_ANVIL.get()), SmithingRecipeCategory.TYPE);
        registration.addRecipeCatalyst(new ItemStack(ModItems.SMITHS_TROUGH.get()), SmithingRecipeCategory.TYPE);
    }
}
